### ISSUE TITLE
Handle re-configured mount roots

### ISSUE THREAD

**Issue by birtles** [mojadev/wsl-path#1]
Many users re-configure the mount root, e.g. setting `/etc/wsl.conf` to:

```
[automount]
root = /
```
e.g. https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

The `wslpath` utility handles this correctly, but `wslToWindows` will complain `Linux path must reside in /mnt/`.

**Comment by mojadev** [comment]
good point, I'll take a look

**Comment by mojadev** [comment]
I fixed this bug in the current master. Would be good if you can test it - I'll release the next version beginning of the week

**Comment by mojadev** [comment]
Fixed in 2.0.0
