### ISSUE TITLE
typescript types is not bundled

### ISSUE THREAD

**Issue by tjx666** [mojadev/wsl-path#27]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/209447833-0149aa04-3769-44a3-a922-c449c5915ad1.png">

check here: https://npmview.vercel.app/wsl-path

**Comment by mojadev** [comment]
Damn, yes - I changed the release process. Will fix it right away. Sorry that this happened in a patch version

**Comment by mojadev** [comment]
Should be fixed now, please try 3.0.3

**Comment by tjx666** [comment]
@mojadev 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/209466689-72819b2e-4bf2-4910-ad5f-f10721612d17.png">

**Comment by mojadev** [comment]
Try again with 3.0.4, I still had the src/** frolder in the npmignore, so it ignored dist/src/...

I tested it with 'resetCache' only, as I currently don't have a windows machine. Thanks for the screenshot

**Comment by tjx666** [comment]
4.0.0 is ok
